// Generated by scripts/report_generator.py — do not edit by hand.
window.REPORT_DATA = {
  "meta": {
    "protocol_name": "Bitcoin",
    "token_symbol": "BTC",
    "date": "2026-04-25",
    "category": null,
    "chains": [
      "Bitcoin"
    ],
    "description": null
  },
  "kpis": [
    {
      "label": "TVL",
      "value": "$5.19B",
      "delta": "+17.34%",
      "trend": "up"
    },
    {
      "label": "Daily Fees",
      "value": "$73.9K",
      "delta": null,
      "trend": null
    },
    {
      "label": "Daily Revenue",
      "value": null,
      "delta": null,
      "trend": null
    },
    {
      "label": "Layer",
      "value": "L1",
      "delta": null,
      "trend": null
    }
  ],
  "metrics": [
    {
      "label": "TVL",
      "value": "$5.19B"
    },
    {
      "label": "7d Change",
      "value": "-0.64%"
    },
    {
      "label": "30d Change",
      "value": "+17.34%"
    },
    {
      "label": "Daily Fees",
      "value": "$73.9K"
    },
    {
      "label": "Daily Revenue",
      "value": null
    },
    {
      "label": "Chains",
      "value": "Bitcoin"
    }
  ],
  "tldr": null,
  "layer": {
    "number": 1,
    "name": "Network / Consensus",
    "stack_description": "Network and consensus layer: validator nodes, staking infrastructure, and client software securing the chain."
  },
  "tvl_history": [
    {
      "date": 1774569600,
      "tvl": 4500663662.0
    },
    {
      "date": 1774656000,
      "tvl": 4351315674.0
    },
    {
      "date": 1774742400,
      "tvl": 4489823658.0
    },
    {
      "date": 1774828800,
      "tvl": 4465897167.0
    },
    {
      "date": 1774915200,
      "tvl": 4541195859.0
    },
    {
      "date": 1775001600,
      "tvl": 4617570840.0
    },
    {
      "date": 1775088000,
      "tvl": 4625713153.0
    },
    {
      "date": 1775174400,
      "tvl": 4525205442.0
    },
    {
      "date": 1775260800,
      "tvl": 4539257290.0
    },
    {
      "date": 1775347200,
      "tvl": 4559197954.0
    },
    {
      "date": 1775433600,
      "tvl": 4686397983.0
    },
    {
      "date": 1775520000,
      "tvl": 4672580784.0
    },
    {
      "date": 1775606400,
      "tvl": 4883263682.0
    },
    {
      "date": 1775692800,
      "tvl": 4811074683.0
    },
    {
      "date": 1775779200,
      "tvl": 4885498621.0
    },
    {
      "date": 1775865600,
      "tvl": 4952552960.0
    },
    {
      "date": 1775952000,
      "tvl": 4960825346.0
    },
    {
      "date": 1776038400,
      "tvl": 4801873408.0
    },
    {
      "date": 1776124800,
      "tvl": 5053182639.0
    },
    {
      "date": 1776211200,
      "tvl": 5060730751.0
    },
    {
      "date": 1776297600,
      "tvl": 5065447292.0
    },
    {
      "date": 1776384000,
      "tvl": 5078624403.0
    },
    {
      "date": 1776470400,
      "tvl": 5224169697.0
    },
    {
      "date": 1776556800,
      "tvl": 5127708051.0
    },
    {
      "date": 1776643200,
      "tvl": 5006854316.0
    },
    {
      "date": 1776729600,
      "tvl": 5125312448.0
    },
    {
      "date": 1776816000,
      "tvl": 5133489353.0
    },
    {
      "date": 1776902400,
      "tvl": 5259568939.0
    },
    {
      "date": 1776988800,
      "tvl": 5243802210.0
    },
    {
      "date": 1777075200,
      "tvl": 5190667982.0
    }
  ],
  "upstream": [],
  "downstream": [],
  "hidden_dependency": null,
  "risk": {
    "score": null,
    "primary_risk": null,
    "reasoning": null
  },
  "comparables": [
    {
      "name": "Ethereum",
      "tvl": 45406353953.456154,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Solana",
      "tvl": 5570079778.432498,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "BSC",
      "tvl": 5564657694.550404,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Bitcoin",
      "tvl": 5191304255.971638,
      "fees_24h": 73859.0,
      "category": null
    },
    {
      "name": "Tron",
      "tvl": 5026211912.131422,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Base",
      "tvl": 4380885056.593381,
      "fees_24h": null,
      "category": null
    }
  ],
  "findings": [],
  "key_insight": null,
  "content_hooks": {
    "video": null,
    "substack": null,
    "x_thread": null
  },
  "tokenomics_notes": null
};
