// Generated by scripts/report_generator.py — do not edit by hand.
window.REPORT_DATA = {
  "meta": {
    "protocol_name": "Arbitrum",
    "token_symbol": "ARB",
    "date": "2026-04-25",
    "category": null,
    "chains": [
      "Arbitrum"
    ],
    "description": null
  },
  "kpis": [
    {
      "label": "TVL",
      "value": "$1.69B",
      "delta": "-15.59%",
      "trend": "down"
    },
    {
      "label": "Daily Fees",
      "value": "$558.0K",
      "delta": null,
      "trend": null
    },
    {
      "label": "Daily Revenue",
      "value": null,
      "delta": null,
      "trend": null
    },
    {
      "label": "Layer",
      "value": "L1",
      "delta": null,
      "trend": null
    }
  ],
  "metrics": [
    {
      "label": "TVL",
      "value": "$1.69B"
    },
    {
      "label": "7d Change",
      "value": "-16.04%"
    },
    {
      "label": "30d Change",
      "value": "-15.59%"
    },
    {
      "label": "Daily Fees",
      "value": "$558.0K"
    },
    {
      "label": "Daily Revenue",
      "value": null
    },
    {
      "label": "Chains",
      "value": "Arbitrum"
    }
  ],
  "tldr": null,
  "layer": {
    "number": 1,
    "name": "Network / Consensus",
    "stack_description": "Network and consensus layer: validator nodes, staking infrastructure, and client software securing the chain."
  },
  "tvl_history": [
    {
      "date": 1774569600,
      "tvl": 1947496066.0
    },
    {
      "date": 1774656000,
      "tvl": 1904490276.0
    },
    {
      "date": 1774742400,
      "tvl": 1901567978.0
    },
    {
      "date": 1774828800,
      "tvl": 1900353974.0
    },
    {
      "date": 1774915200,
      "tvl": 1910566367.0
    },
    {
      "date": 1775001600,
      "tvl": 1930690265.0
    },
    {
      "date": 1775088000,
      "tvl": 1947602202.0
    },
    {
      "date": 1775174400,
      "tvl": 1904530534.0
    },
    {
      "date": 1775260800,
      "tvl": 1895603603.0
    },
    {
      "date": 1775347200,
      "tvl": 1895692633.0
    },
    {
      "date": 1775433600,
      "tvl": 1922633098.0
    },
    {
      "date": 1775520000,
      "tvl": 1904794002.0
    },
    {
      "date": 1775606400,
      "tvl": 1967588288.0
    },
    {
      "date": 1775692800,
      "tvl": 1918103535.0
    },
    {
      "date": 1775779200,
      "tvl": 1921129515.0
    },
    {
      "date": 1775865600,
      "tvl": 1938245089.0
    },
    {
      "date": 1775952000,
      "tvl": 1946893409.0
    },
    {
      "date": 1776038400,
      "tvl": 1916902460.0
    },
    {
      "date": 1776124800,
      "tvl": 1986618598.0
    },
    {
      "date": 1776211200,
      "tvl": 1966286260.0
    },
    {
      "date": 1776297600,
      "tvl": 1987609774.0
    },
    {
      "date": 1776384000,
      "tvl": 1985000267.0
    },
    {
      "date": 1776470400,
      "tvl": 2018081279.0
    },
    {
      "date": 1776556800,
      "tvl": 1944598736.0
    },
    {
      "date": 1776643200,
      "tvl": 1783123644.0
    },
    {
      "date": 1776729600,
      "tvl": 1712667389.0
    },
    {
      "date": 1776816000,
      "tvl": 1698476967.0
    },
    {
      "date": 1776902400,
      "tvl": 1730526876.0
    },
    {
      "date": 1776988800,
      "tvl": 1701985527.0
    },
    {
      "date": 1777075200,
      "tvl": 1694432633.0
    }
  ],
  "upstream": [],
  "downstream": [],
  "hidden_dependency": null,
  "risk": {
    "score": null,
    "primary_risk": null,
    "reasoning": null
  },
  "comparables": [
    {
      "name": "Ethereum",
      "tvl": 45406353953.456154,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Solana",
      "tvl": 5570079778.432498,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "BSC",
      "tvl": 5564657694.550404,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Bitcoin",
      "tvl": 5191304255.971638,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Tron",
      "tvl": 5026211912.131422,
      "fees_24h": null,
      "category": null
    },
    {
      "name": "Arbitrum",
      "tvl": 1694480869.9917226,
      "fees_24h": 558010.0,
      "category": null
    }
  ],
  "findings": [],
  "key_insight": null,
  "content_hooks": {
    "video": null,
    "substack": null,
    "x_thread": null
  },
  "tokenomics_notes": null
};
